import { Drawer } from "@/components/drawer/Drawer";
import { Layout } from "@/components/layout/Layout";
import { NavBar } from "@/components/navBar/NavBar";
import { useState } from "react";

export default function Home(p: { text: string }) {
  return (
    <>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
      <div>asddsaadasasasd</div>
    </>
  );
}
